# Generated by Django 4.2.13 on 2024-05-17 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_details_ID', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('item_size', models.CharField(max_length=200)),
                ('item_color', models.CharField(max_length=200)),
                ('item_cost', models.CharField(max_length=200)),
                ('item_quantity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='order_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.CharField(max_length=200)),
                ('distribution_date', models.CharField(max_length=200)),
                ('order_status', models.CharField(max_length=200)),
                ('payment_method', models.CharField(max_length=200)),
                ('payment_status', models.CharField(max_length=200)),
                ('order_details_ID', models.CharField(default='0', max_length=200)),
                ('user_info_ID', models.CharField(default='000000000', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]{1,9}$', 'Student ID must be numeric and have at most 9 digits.')])),
                ('student_name', models.CharField(max_length=200)),
            ],
        ),
    ]
