# Generated by Django 4.2.13 on 2024-05-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='order_details_ID',
            new_name='order_details_id',
        ),
        migrations.RenameField(
            model_name='order_info',
            old_name='order_details_ID',
            new_name='order_details_id',
        ),
        migrations.RenameField(
            model_name='order_info',
            old_name='user_info_ID',
            new_name='user_info_id',
        ),
    ]
