# Generated by Django 4.2.13 on 2024-05-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_contact_us_email_alter_contact_us_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info',
            name='order_details_id',
            field=models.CharField(max_length=200),
        ),
    ]
