# Generated by Django 4.2.13 on 2024-05-19 11:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_order_info_order_details_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='id',
        ),
        migrations.AddField(
            model_name='user_info',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order_info',
            name='order_details_id',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='student_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{1,9}$', 'Student ID must be numeric and have at most 9 digits.')]),
        ),
    ]
