# Generated by Django 4.2.13 on 2024-05-19 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_user_info_id_user_info_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
