# Generated by Django 4.2.13 on 2024-05-26 10:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contact_us_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('fulfillmentId', models.AutoField(primary_key=True, serialize=False)),
                ('fulfillmentDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fulfillment',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=50)),
                ('estimatedDeliveryDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('orderItemId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customerNote', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('paymentDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentMethod', models.CharField(max_length=50)),
                ('paymentStatus', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product',
                'indexes': [models.Index(fields=['productId'], name='product_id_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('productId',), name='unique_product_id'),
        ),
        migrations.AddField(
            model_name='payment',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='productId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='orderId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.order'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customerId'], name='customer_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('customerId',), name='unique_customer_id'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paymentId'], name='payment_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('paymentId',), name='unique_payment_id'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['orderItemId'], name='order_item_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('orderItemId',), name='unique_order_item_id'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['orderId'], name='order_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('orderId',), name='unique_order_id'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['inventoryId'], name='inventory_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('inventoryId',), name='unique_inventory_id'),
        ),
        migrations.AddIndex(
            model_name='fulfillment',
            index=models.Index(fields=['fulfillmentId'], name='fulfillment_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='fulfillment',
            constraint=models.UniqueConstraint(fields=('fulfillmentId',), name='unique_fulfillment_id'),
        ),
    ]
