# Generated by Django 4.2.13 on 2024-05-26 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_remove_customer_unique_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='processedBy',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, related_name='processed_fulfillments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='discountAmount',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='processedBy',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, related_name='processed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='totalAmount',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='customerId',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processedBy',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='referenceNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='customerId',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentStatus',
            field=models.CharField(default='For Verification', max_length=50),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('logId', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(max_length=255)),
                ('system_text', models.TextField()),
                ('user_text', models.TextField()),
                ('created_by', models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
            options={
                'db_table': 'log',
                'indexes': [models.Index(fields=['logId'], name='logId_id_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='log',
            constraint=models.UniqueConstraint(fields=('logId',), name='unique_logId_id'),
        ),
    ]
