# Generated by Django 4.2.13 on 2024-05-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_fulfillment_processedby_order_discountamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
