# Generated by Django 4.2.13 on 2024-06-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actualDeliveryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
