# Generated by Django 5.0.6 on 2024-06-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_order_actualdeliverydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='actualDeliveryDate',
        ),
    ]
