# Generated by Django 5.0.6 on 2024-06-04 18:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_order_actualdeliverydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('question1', models.IntegerField(choices=[(1, 'Not at all'), (2, 'Somewhat'), (3, 'Very'), (4, 'Completely')])),
                ('question2', models.IntegerField(choices=[(1, 'Difficult'), (2, 'Neutral'), (3, 'Easy'), (4, 'Very Easy')])),
                ('question3', models.IntegerField(choices=[(1, 'Not at all'), (2, 'Somewhat'), (3, 'Very'), (4, 'Completely')])),
                ('question4', models.IntegerField(choices=[(1, 'Unlikely'), (2, 'Neutral'), (3, 'Likely'), (4, 'Very Likely')])),
                ('comments', models.TextField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
            ],
            options={
                'db_table': 'customer_satisfaction_survey',
            },
        ),
        migrations.AddConstraint(
            model_name='customersatisfactionsurvey',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_order_survey'),
        ),
    ]
