# Generated by Django 4.2.13 on 2024-06-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_log_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
